### ISSUE TITLE
Error while running example code

### ISSUE THREAD

**Issue by punund** [FilenCloudDienste/filen-webdav#67]
**Describe the bug**
Example code is not working

**To Reproduce**

Follow README, try to run the server code

**Expected behavior**
It is expected at least to compile

**Screenshots**
const filen = new FilenSDK({
              ^

TypeError: FilenSDK is not a constructor
    at  .......... main.js:9:15
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.18.0
**OS (please complete the following information):**

-   OS: Ubuntu 22.04

**Additional context**

**Comment by Dwynr** [comment]
Looks like you do not have all the needed dependencies installed. You'll need `@filen/sdk` and `@filen/webdav` (from npm) to run the example.

**Comment by punund** [comment]
I certainly do, otherwise it would've failed at the import:
```js
import FilenSDK from "@filen/sdk"
```
Complete `package.json`:
```json
{
  "name": "example",
  "version": "1.0.0",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "@filen/sdk": "^0.1.174",
    "@filen/webdav": "^0.2.55"
  }
}
```

**Comment by Dwynr** [comment]
What moduleResolution setting are you using? If you are running typescript set it to `"node"`. If you are running a bundler (e.g. Webpack/esbuild etc.) make sure it can import ESModules.

**Comment by punund** [comment]
There is no typescipt, no webpack and no transpilation, none of it is listed as dependency.
I assumed that the modules are standard compliant ES6.
I just run node, which is capable of importing ES modules since version 15.
```
❯ node -v
v22.11.0
```
